# path to folder of data for all subjects
bids_root: "/Volumes/Mac/research/data/efri/"

# path to folder of transformed data
derivatives_path: "/Users/ChesterHuynh/Johns Hopkins/Adam Li - efri/derivatives/"

# path to folder of results and figures
results_path: "/Users/ChesterHuynh/Johns Hopkins/Adam Li - efri/derivatives/workstation_output"
